/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedLayoutRouteImport } from './routes/_authenticated/layout'
import { Route as PageRouteImport } from './routes/page'
import { Route as AuthenticatedSettingsLayoutRouteImport } from './routes/_authenticated/settings/layout'
import { Route as AuthenticatedDashboardLayoutRouteImport } from './routes/_authenticated/_dashboard/layout'
import { Route as AuthenticatedSettingsPageRouteImport } from './routes/_authenticated/settings/page'
import { Route as AuthenticatedSettingsTerminalPageRouteImport } from './routes/_authenticated/settings/terminal/page'
import { Route as AuthenticatedSettingsTasksPageRouteImport } from './routes/_authenticated/settings/tasks/page'
import { Route as AuthenticatedSettingsSpacesPageRouteImport } from './routes/_authenticated/settings/spaces/page'
import { Route as AuthenticatedSettingsRingtonesPageRouteImport } from './routes/_authenticated/settings/ringtones/page'
import { Route as AuthenticatedSettingsPresetsPageRouteImport } from './routes/_authenticated/settings/presets/page'
import { Route as AuthenticatedSettingsPermissionsPageRouteImport } from './routes/_authenticated/settings/permissions/page'
import { Route as AuthenticatedSettingsModelsPageRouteImport } from './routes/_authenticated/settings/models/page'
import { Route as AuthenticatedSettingsMemoryPageRouteImport } from './routes/_authenticated/settings/memory/page'
import { Route as AuthenticatedSettingsKeyboardPageRouteImport } from './routes/_authenticated/settings/keyboard/page'
import { Route as AuthenticatedSettingsGitPageRouteImport } from './routes/_authenticated/settings/git/page'
import { Route as AuthenticatedSettingsBehaviorPageRouteImport } from './routes/_authenticated/settings/behavior/page'
import { Route as AuthenticatedSettingsAppearancePageRouteImport } from './routes/_authenticated/settings/appearance/page'
import { Route as AuthenticatedDashboardWorkspacesPageRouteImport } from './routes/_authenticated/_dashboard/workspaces/page'
import { Route as AuthenticatedDashboardWorkspacePageRouteImport } from './routes/_authenticated/_dashboard/workspace/page'
import { Route as AuthenticatedDashboardTasksPageRouteImport } from './routes/_authenticated/_dashboard/tasks/page'
import { Route as AuthenticatedDashboardWorkspaceWorkspaceIdPageRouteImport } from './routes/_authenticated/_dashboard/workspace/$workspaceId/page'

const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsLayoutRoute =
  AuthenticatedSettingsLayoutRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedDashboardLayoutRoute =
  AuthenticatedDashboardLayoutRouteImport.update({
    id: '/_dashboard',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedSettingsPageRoute =
  AuthenticatedSettingsPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsTerminalPageRoute =
  AuthenticatedSettingsTerminalPageRouteImport.update({
    id: '/terminal/',
    path: '/terminal/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsTasksPageRoute =
  AuthenticatedSettingsTasksPageRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsSpacesPageRoute =
  AuthenticatedSettingsSpacesPageRouteImport.update({
    id: '/spaces/',
    path: '/spaces/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsRingtonesPageRoute =
  AuthenticatedSettingsRingtonesPageRouteImport.update({
    id: '/ringtones/',
    path: '/ringtones/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsPresetsPageRoute =
  AuthenticatedSettingsPresetsPageRouteImport.update({
    id: '/presets/',
    path: '/presets/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsPermissionsPageRoute =
  AuthenticatedSettingsPermissionsPageRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsModelsPageRoute =
  AuthenticatedSettingsModelsPageRouteImport.update({
    id: '/models/',
    path: '/models/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsMemoryPageRoute =
  AuthenticatedSettingsMemoryPageRouteImport.update({
    id: '/memory/',
    path: '/memory/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsKeyboardPageRoute =
  AuthenticatedSettingsKeyboardPageRouteImport.update({
    id: '/keyboard/',
    path: '/keyboard/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsGitPageRoute =
  AuthenticatedSettingsGitPageRouteImport.update({
    id: '/git/',
    path: '/git/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsBehaviorPageRoute =
  AuthenticatedSettingsBehaviorPageRouteImport.update({
    id: '/behavior/',
    path: '/behavior/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsAppearancePageRoute =
  AuthenticatedSettingsAppearancePageRouteImport.update({
    id: '/appearance/',
    path: '/appearance/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedDashboardWorkspacesPageRoute =
  AuthenticatedDashboardWorkspacesPageRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardWorkspacePageRoute =
  AuthenticatedDashboardWorkspacePageRouteImport.update({
    id: '/workspace/',
    path: '/workspace/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardTasksPageRoute =
  AuthenticatedDashboardTasksPageRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardWorkspaceWorkspaceIdPageRoute =
  AuthenticatedDashboardWorkspaceWorkspaceIdPageRouteImport.update({
    id: '/workspace/$workspaceId/',
    path: '/workspace/$workspaceId/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PageRoute
  '/settings': typeof AuthenticatedSettingsLayoutRouteWithChildren
  '/settings/': typeof AuthenticatedSettingsPageRoute
  '/tasks/': typeof AuthenticatedDashboardTasksPageRoute
  '/workspace/': typeof AuthenticatedDashboardWorkspacePageRoute
  '/workspaces/': typeof AuthenticatedDashboardWorkspacesPageRoute
  '/settings/appearance/': typeof AuthenticatedSettingsAppearancePageRoute
  '/settings/behavior/': typeof AuthenticatedSettingsBehaviorPageRoute
  '/settings/git/': typeof AuthenticatedSettingsGitPageRoute
  '/settings/keyboard/': typeof AuthenticatedSettingsKeyboardPageRoute
  '/settings/memory/': typeof AuthenticatedSettingsMemoryPageRoute
  '/settings/models/': typeof AuthenticatedSettingsModelsPageRoute
  '/settings/permissions/': typeof AuthenticatedSettingsPermissionsPageRoute
  '/settings/presets/': typeof AuthenticatedSettingsPresetsPageRoute
  '/settings/ringtones/': typeof AuthenticatedSettingsRingtonesPageRoute
  '/settings/spaces/': typeof AuthenticatedSettingsSpacesPageRoute
  '/settings/tasks/': typeof AuthenticatedSettingsTasksPageRoute
  '/settings/terminal/': typeof AuthenticatedSettingsTerminalPageRoute
  '/workspace/$workspaceId/': typeof AuthenticatedDashboardWorkspaceWorkspaceIdPageRoute
}
export interface FileRoutesByTo {
  '/': typeof PageRoute
  '/settings': typeof AuthenticatedSettingsPageRoute
  '/tasks': typeof AuthenticatedDashboardTasksPageRoute
  '/workspace': typeof AuthenticatedDashboardWorkspacePageRoute
  '/workspaces': typeof AuthenticatedDashboardWorkspacesPageRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearancePageRoute
  '/settings/behavior': typeof AuthenticatedSettingsBehaviorPageRoute
  '/settings/git': typeof AuthenticatedSettingsGitPageRoute
  '/settings/keyboard': typeof AuthenticatedSettingsKeyboardPageRoute
  '/settings/memory': typeof AuthenticatedSettingsMemoryPageRoute
  '/settings/models': typeof AuthenticatedSettingsModelsPageRoute
  '/settings/permissions': typeof AuthenticatedSettingsPermissionsPageRoute
  '/settings/presets': typeof AuthenticatedSettingsPresetsPageRoute
  '/settings/ringtones': typeof AuthenticatedSettingsRingtonesPageRoute
  '/settings/spaces': typeof AuthenticatedSettingsSpacesPageRoute
  '/settings/tasks': typeof AuthenticatedSettingsTasksPageRoute
  '/settings/terminal': typeof AuthenticatedSettingsTerminalPageRoute
  '/workspace/$workspaceId': typeof AuthenticatedDashboardWorkspaceWorkspaceIdPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof PageRoute
  '/_authenticated': typeof AuthenticatedLayoutRouteWithChildren
  '/_authenticated/_dashboard': typeof AuthenticatedDashboardLayoutRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsLayoutRouteWithChildren
  '/_authenticated/settings/': typeof AuthenticatedSettingsPageRoute
  '/_authenticated/_dashboard/tasks/': typeof AuthenticatedDashboardTasksPageRoute
  '/_authenticated/_dashboard/workspace/': typeof AuthenticatedDashboardWorkspacePageRoute
  '/_authenticated/_dashboard/workspaces/': typeof AuthenticatedDashboardWorkspacesPageRoute
  '/_authenticated/settings/appearance/': typeof AuthenticatedSettingsAppearancePageRoute
  '/_authenticated/settings/behavior/': typeof AuthenticatedSettingsBehaviorPageRoute
  '/_authenticated/settings/git/': typeof AuthenticatedSettingsGitPageRoute
  '/_authenticated/settings/keyboard/': typeof AuthenticatedSettingsKeyboardPageRoute
  '/_authenticated/settings/memory/': typeof AuthenticatedSettingsMemoryPageRoute
  '/_authenticated/settings/models/': typeof AuthenticatedSettingsModelsPageRoute
  '/_authenticated/settings/permissions/': typeof AuthenticatedSettingsPermissionsPageRoute
  '/_authenticated/settings/presets/': typeof AuthenticatedSettingsPresetsPageRoute
  '/_authenticated/settings/ringtones/': typeof AuthenticatedSettingsRingtonesPageRoute
  '/_authenticated/settings/spaces/': typeof AuthenticatedSettingsSpacesPageRoute
  '/_authenticated/settings/tasks/': typeof AuthenticatedSettingsTasksPageRoute
  '/_authenticated/settings/terminal/': typeof AuthenticatedSettingsTerminalPageRoute
  '/_authenticated/_dashboard/workspace/$workspaceId/': typeof AuthenticatedDashboardWorkspaceWorkspaceIdPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/settings/'
    | '/tasks/'
    | '/workspace/'
    | '/workspaces/'
    | '/settings/appearance/'
    | '/settings/behavior/'
    | '/settings/git/'
    | '/settings/keyboard/'
    | '/settings/memory/'
    | '/settings/models/'
    | '/settings/permissions/'
    | '/settings/presets/'
    | '/settings/ringtones/'
    | '/settings/spaces/'
    | '/settings/tasks/'
    | '/settings/terminal/'
    | '/workspace/$workspaceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/tasks'
    | '/workspace'
    | '/workspaces'
    | '/settings/appearance'
    | '/settings/behavior'
    | '/settings/git'
    | '/settings/keyboard'
    | '/settings/memory'
    | '/settings/models'
    | '/settings/permissions'
    | '/settings/presets'
    | '/settings/ringtones'
    | '/settings/spaces'
    | '/settings/tasks'
    | '/settings/terminal'
    | '/workspace/$workspaceId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/_dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/settings/'
    | '/_authenticated/_dashboard/tasks/'
    | '/_authenticated/_dashboard/workspace/'
    | '/_authenticated/_dashboard/workspaces/'
    | '/_authenticated/settings/appearance/'
    | '/_authenticated/settings/behavior/'
    | '/_authenticated/settings/git/'
    | '/_authenticated/settings/keyboard/'
    | '/_authenticated/settings/memory/'
    | '/_authenticated/settings/models/'
    | '/_authenticated/settings/permissions/'
    | '/_authenticated/settings/presets/'
    | '/_authenticated/settings/ringtones/'
    | '/_authenticated/settings/spaces/'
    | '/_authenticated/settings/tasks/'
    | '/_authenticated/settings/terminal/'
    | '/_authenticated/_dashboard/workspace/$workspaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PageRoute: typeof PageRoute
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsLayoutRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_dashboard': {
      id: '/_authenticated/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/terminal/': {
      id: '/_authenticated/settings/terminal/'
      path: '/terminal'
      fullPath: '/settings/terminal/'
      preLoaderRoute: typeof AuthenticatedSettingsTerminalPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/tasks/': {
      id: '/_authenticated/settings/tasks/'
      path: '/tasks'
      fullPath: '/settings/tasks/'
      preLoaderRoute: typeof AuthenticatedSettingsTasksPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/spaces/': {
      id: '/_authenticated/settings/spaces/'
      path: '/spaces'
      fullPath: '/settings/spaces/'
      preLoaderRoute: typeof AuthenticatedSettingsSpacesPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/ringtones/': {
      id: '/_authenticated/settings/ringtones/'
      path: '/ringtones'
      fullPath: '/settings/ringtones/'
      preLoaderRoute: typeof AuthenticatedSettingsRingtonesPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/presets/': {
      id: '/_authenticated/settings/presets/'
      path: '/presets'
      fullPath: '/settings/presets/'
      preLoaderRoute: typeof AuthenticatedSettingsPresetsPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/permissions/': {
      id: '/_authenticated/settings/permissions/'
      path: '/permissions'
      fullPath: '/settings/permissions/'
      preLoaderRoute: typeof AuthenticatedSettingsPermissionsPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/models/': {
      id: '/_authenticated/settings/models/'
      path: '/models'
      fullPath: '/settings/models/'
      preLoaderRoute: typeof AuthenticatedSettingsModelsPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/memory/': {
      id: '/_authenticated/settings/memory/'
      path: '/memory'
      fullPath: '/settings/memory/'
      preLoaderRoute: typeof AuthenticatedSettingsMemoryPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/keyboard/': {
      id: '/_authenticated/settings/keyboard/'
      path: '/keyboard'
      fullPath: '/settings/keyboard/'
      preLoaderRoute: typeof AuthenticatedSettingsKeyboardPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/git/': {
      id: '/_authenticated/settings/git/'
      path: '/git'
      fullPath: '/settings/git/'
      preLoaderRoute: typeof AuthenticatedSettingsGitPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/behavior/': {
      id: '/_authenticated/settings/behavior/'
      path: '/behavior'
      fullPath: '/settings/behavior/'
      preLoaderRoute: typeof AuthenticatedSettingsBehaviorPageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/appearance/': {
      id: '/_authenticated/settings/appearance/'
      path: '/appearance'
      fullPath: '/settings/appearance/'
      preLoaderRoute: typeof AuthenticatedSettingsAppearancePageRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/_dashboard/workspaces/': {
      id: '/_authenticated/_dashboard/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AuthenticatedDashboardWorkspacesPageRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/_dashboard/workspace/': {
      id: '/_authenticated/_dashboard/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof AuthenticatedDashboardWorkspacePageRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/_dashboard/tasks/': {
      id: '/_authenticated/_dashboard/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedDashboardTasksPageRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/_dashboard/workspace/$workspaceId/': {
      id: '/_authenticated/_dashboard/workspace/$workspaceId/'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof AuthenticatedDashboardWorkspaceWorkspaceIdPageRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
  }
}

interface AuthenticatedDashboardLayoutRouteChildren {
  AuthenticatedDashboardTasksPageRoute: typeof AuthenticatedDashboardTasksPageRoute
  AuthenticatedDashboardWorkspacePageRoute: typeof AuthenticatedDashboardWorkspacePageRoute
  AuthenticatedDashboardWorkspacesPageRoute: typeof AuthenticatedDashboardWorkspacesPageRoute
  AuthenticatedDashboardWorkspaceWorkspaceIdPageRoute: typeof AuthenticatedDashboardWorkspaceWorkspaceIdPageRoute
}

const AuthenticatedDashboardLayoutRouteChildren: AuthenticatedDashboardLayoutRouteChildren =
  {
    AuthenticatedDashboardTasksPageRoute: AuthenticatedDashboardTasksPageRoute,
    AuthenticatedDashboardWorkspacePageRoute:
      AuthenticatedDashboardWorkspacePageRoute,
    AuthenticatedDashboardWorkspacesPageRoute:
      AuthenticatedDashboardWorkspacesPageRoute,
    AuthenticatedDashboardWorkspaceWorkspaceIdPageRoute:
      AuthenticatedDashboardWorkspaceWorkspaceIdPageRoute,
  }

const AuthenticatedDashboardLayoutRouteWithChildren =
  AuthenticatedDashboardLayoutRoute._addFileChildren(
    AuthenticatedDashboardLayoutRouteChildren,
  )

interface AuthenticatedSettingsLayoutRouteChildren {
  AuthenticatedSettingsPageRoute: typeof AuthenticatedSettingsPageRoute
  AuthenticatedSettingsAppearancePageRoute: typeof AuthenticatedSettingsAppearancePageRoute
  AuthenticatedSettingsBehaviorPageRoute: typeof AuthenticatedSettingsBehaviorPageRoute
  AuthenticatedSettingsGitPageRoute: typeof AuthenticatedSettingsGitPageRoute
  AuthenticatedSettingsKeyboardPageRoute: typeof AuthenticatedSettingsKeyboardPageRoute
  AuthenticatedSettingsMemoryPageRoute: typeof AuthenticatedSettingsMemoryPageRoute
  AuthenticatedSettingsModelsPageRoute: typeof AuthenticatedSettingsModelsPageRoute
  AuthenticatedSettingsPermissionsPageRoute: typeof AuthenticatedSettingsPermissionsPageRoute
  AuthenticatedSettingsPresetsPageRoute: typeof AuthenticatedSettingsPresetsPageRoute
  AuthenticatedSettingsRingtonesPageRoute: typeof AuthenticatedSettingsRingtonesPageRoute
  AuthenticatedSettingsSpacesPageRoute: typeof AuthenticatedSettingsSpacesPageRoute
  AuthenticatedSettingsTasksPageRoute: typeof AuthenticatedSettingsTasksPageRoute
  AuthenticatedSettingsTerminalPageRoute: typeof AuthenticatedSettingsTerminalPageRoute
}

const AuthenticatedSettingsLayoutRouteChildren: AuthenticatedSettingsLayoutRouteChildren =
  {
    AuthenticatedSettingsPageRoute: AuthenticatedSettingsPageRoute,
    AuthenticatedSettingsAppearancePageRoute:
      AuthenticatedSettingsAppearancePageRoute,
    AuthenticatedSettingsBehaviorPageRoute:
      AuthenticatedSettingsBehaviorPageRoute,
    AuthenticatedSettingsGitPageRoute: AuthenticatedSettingsGitPageRoute,
    AuthenticatedSettingsKeyboardPageRoute:
      AuthenticatedSettingsKeyboardPageRoute,
    AuthenticatedSettingsMemoryPageRoute: AuthenticatedSettingsMemoryPageRoute,
    AuthenticatedSettingsModelsPageRoute: AuthenticatedSettingsModelsPageRoute,
    AuthenticatedSettingsPermissionsPageRoute:
      AuthenticatedSettingsPermissionsPageRoute,
    AuthenticatedSettingsPresetsPageRoute:
      AuthenticatedSettingsPresetsPageRoute,
    AuthenticatedSettingsRingtonesPageRoute:
      AuthenticatedSettingsRingtonesPageRoute,
    AuthenticatedSettingsSpacesPageRoute: AuthenticatedSettingsSpacesPageRoute,
    AuthenticatedSettingsTasksPageRoute: AuthenticatedSettingsTasksPageRoute,
    AuthenticatedSettingsTerminalPageRoute:
      AuthenticatedSettingsTerminalPageRoute,
  }

const AuthenticatedSettingsLayoutRouteWithChildren =
  AuthenticatedSettingsLayoutRoute._addFileChildren(
    AuthenticatedSettingsLayoutRouteChildren,
  )

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedDashboardLayoutRoute: typeof AuthenticatedDashboardLayoutRouteWithChildren
  AuthenticatedSettingsLayoutRoute: typeof AuthenticatedSettingsLayoutRouteWithChildren
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedDashboardLayoutRoute:
    AuthenticatedDashboardLayoutRouteWithChildren,
  AuthenticatedSettingsLayoutRoute:
    AuthenticatedSettingsLayoutRouteWithChildren,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRoute,
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
